/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

"use client";

import React, { useRef, useLayoutEffect } from "react";
import { useGLTF, useScroll } from "@react-three/drei";
import App from './App'

createRoot(document.getElementById('root')).render(<App />)


//BELOW THIS IS VERY IMPORTANT MUST ADD THIS
useGLTF.preload("./models/robot/phantoms-transformed.glb");
